<div class="min-h-screen bg-slate-100 p-6 text-slate-900">
@include('livewire.finance._header', ['title'=>'Finance Dashboard','subtitle'=>'Material inventory postings are now part of finance automatically.'])
@include('livewire.finance._nav')
<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
<div class="bg-white border p-5"><p class="text-[10px] uppercase font-bold text-slate-500">Inventory Asset</p><p class="text-3xl font-black font-mono text-green-700">{{ number_format($inventoryAsset,2) }}</p></div>
<div class="bg-white border p-5"><p class="text-[10px] uppercase font-bold text-slate-500">Project Material Cost</p><p class="text-3xl font-black font-mono text-blue-700">{{ number_format($projectMaterialCost,2) }}</p></div>
<div class="bg-white border p-5"><p class="text-[10px] uppercase font-bold text-slate-500">Material Receivables</p><p class="text-3xl font-black font-mono text-amber-700">{{ number_format($materialReceivables,2) }}</p></div>
<div class="bg-white border p-5"><p class="text-[10px] uppercase font-bold text-slate-500">Material Revenue</p><p class="text-3xl font-black font-mono text-purple-700">{{ number_format($materialRevenue,2) }}</p></div>
</div>
<div class="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6">
<div class="bg-white border p-5"><p class="text-[10px] uppercase font-bold text-slate-500">COGS</p><p class="text-2xl font-black font-mono text-red-700">{{ number_format($costOfGoodsSold,2) }}</p></div>
<div class="bg-white border p-5"><p class="text-[10px] uppercase font-bold text-slate-500">Net Material Position</p><p class="text-2xl font-black font-mono text-indigo-700">{{ number_format($netMaterialPosition,2) }}</p></div>
<div class="bg-white border p-5"><p class="text-[10px] uppercase font-bold text-slate-500">GL Material Entries</p><p class="text-2xl font-black font-mono">{{ $materialPostingsCount }}</p></div>
<div class="bg-white border border-red-300 p-5"><p class="text-[10px] uppercase font-bold text-red-600">Pending Materials</p><p class="text-2xl font-black font-mono text-red-700">{{ $materialTransactionsPending }}</p></div>
<div class="bg-white border border-green-300 p-5"><p class="text-[10px] uppercase font-bold text-green-600">Approved Materials</p><p class="text-2xl font-black font-mono text-green-700">{{ $materialTransactionsApproved }}</p></div>
</div>
<div class="grid grid-cols-1 xl:grid-cols-3 gap-6">
<div class="xl:col-span-2 bg-white border border-slate-300"><div class="bg-slate-800 text-white px-4 py-3"><h2 class="text-xs uppercase font-bold">Recent Material Finance Postings</h2></div><div class="overflow-x-auto"><table class="w-full text-xs"><thead class="bg-slate-100"><tr><th class="p-3 text-left">Date</th><th class="p-3 text-left">Account</th><th class="p-3 text-left">Reference</th><th class="p-3 text-left">Narration</th><th class="p-3 text-right">Debit</th><th class="p-3 text-right">Credit</th></tr></thead><tbody class="divide-y">@forelse($recentMaterialPostings as $entry)<tr><td class="p-3">{{ $entry->entry_date?->format('d M Y') ?? $entry->transaction_date?->format('d M Y') }}</td><td class="p-3 font-semibold">{{ $entry->account_name ?? $entry->account }}</td><td class="p-3 font-mono">{{ $entry->reference }}</td><td class="p-3">{{ $entry->description ?? $entry->narration }}</td><td class="p-3 text-right font-mono">{{ number_format((float)($entry->debit ?? $entry->debit_amount ?? 0),2) }}</td><td class="p-3 text-right font-mono">{{ number_format((float)($entry->credit ?? $entry->credit_amount ?? 0),2) }}</td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-400 font-bold">No Material Finance Entries Found</td></tr>@endforelse</tbody></table></div></div>
<div class="bg-white border border-slate-300"><div class="bg-slate-800 text-white px-4 py-3"><h2 class="text-xs uppercase font-bold">Material Account Summary</h2></div><div class="divide-y">@foreach($postingSummary as $row)<div class="p-4"><p class="font-bold text-xs">{{ $row['account'] }}</p><div class="grid grid-cols-3 gap-2 mt-2 text-[11px]"><div><span class="text-slate-500">Debit</span><p class="font-mono font-bold">{{ number_format($row['debit'],2) }}</p></div><div><span class="text-slate-500">Credit</span><p class="font-mono font-bold">{{ number_format($row['credit'],2) }}</p></div><div><span class="text-slate-500">Balance</span><p class="font-mono font-bold">{{ number_format($row['balance'],2) }}</p></div></div></div>@endforeach</div></div>
</div>
</div>
